cc_binary(
    name = "main",
    srcs = ["main.cc"],
)

cc_test(
    name = "huffman_test",
    size = "small",
    srcs = ["huffman_test.cc"],
    deps = [
        "@googletest//:gtest",
        "@googletest//:gtest_main",
    ],
)